steps:
- name: ubuntu
  entrypoint: bash
  args: ['-c', 'printenv > .env.production']
  env:
    - 'SMTP_USER=${_SMTP_USER}'
    - 'SMTP_PASS=${_SMTP_PASS}'
    - 'SMTP_HOST=${_SMTP_HOST}'
    - 'SMTP_PORT=${_SMTP_PORT}'
    - 'CLOUD_BUILD=${_CLOUD_BUILD}'
    - 'FIREBASE_SERVICE_KEY=${_FIREBASE_SERVICE_KEY}'
    - 'SESSION_SECRET=${_SESSION_SECRET}'
    - 'NEXT_PUBLIC_LANDING_PAGE_URL=${_NEXT_PUBLIC_LANDING_PAGE_URL}'
    - 'APP_ENV=beta'
    - 'NEXT_PUBLIC_PLATFORM_URL=${_NEXT_PUBLIC_PLATFORM_URL}'
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app-platform-beta', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/nextjs-app-platform-beta']
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'nextjs-app-platform-beta', '--image', 'gcr.io/$PROJECT_ID/nextjs-app-platform-beta:latest', '--platform', 'managed', '--allow-unauthenticated', '--region', 'europe-west3']
- name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: cloud-functions
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/firebase', '-f', './Dockerfile-firebase', '.']
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'hosting:beta', '-P', 'default']
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'functions', '-P', 'asker-beta']
##
images:
- gcr.io/$PROJECT_ID/nextjs-app-platform-beta
timeout: 900s
